const  glossary = {
  "CRVENA ZVEZDA": "Црвена Звезда",
  "CZECH REPUBLIC": "Чехия",
  ARGENTINA: "Аргентина",
  "ATLÉTICO DE MADRID": "Атлетико Мадрид",
  "ATHLETIC BILBAO": "Атлетик Бильбао",
  AUSTRALIA: "Австралия",
  BARCELONA: "Барселона",
  "BERGAMO CALCIO": "Бергамо",
  "BORUSSIA DORTMUND": "Боруссия Дортмунд",
  CANADA: "Канада",
  CHELSEA: "Челси",
  CHINA: "Китай",
  CSKA: "ЦСКА",
  ENGLAND: "Англия",
  EUROPE: "Европа",
  "FC BARCELONA": "Барселона",
  "FC PORTO": "Порту",
  FENERBAHCE: "Фенербахче",
  FINLAND: "Финляндия",
  FRANCE: "Франция",
  GERMANY: "Германия",
  GREECE: "Греция",
  ITALY: "Италия",
  LEVERKUSEN: "Байер 04",
  LATIUM: "Лацио",
  "LEICESTER CITY": "Лестер Сити",
  LIVERPOOL: "Ливерпуль",
  "LOSC LILLE": "Лилль",
  LYON: "Лион",
  "M'GLADBACH": "Боруссия Мёнхенгладбах",
  MACCABI: "Маккаби",
  MARSEILLE: "Марсель",
  "MANCHESTER UTD": "Манчестер Юнайтед",
  MILAN: "Милан",
  NAPOLI: "Наполи",
  NETHERLANDS: "Нидерланды",
  "NORTH AMERICA": "Северная Америка",
  OLYMPIACOS: "Олимпиакос",
  PANATHINAIKOS: "Панатинаикос",
  PORTUGAL: "Португалия",
  REAL: "Реал",
  "REAL BETIS": "Реал Бетис",
  "ROMA FC": "Рома",
  RUSSIA: "Россия",
  "SEVILLA FC": "Севилья",
  "SL BENFICA": "Бенфика",
  SLOVENIA: "Словения",
  SPAIN: "Испания",
  SWEDEN: "Швеция",
  SWITZERLAND: "Швейцария",
  "TSG HOFFENHEIM": "Хоффенхайм",
  UNICS: "УНИКС",
  USA: "США",
 "VFL WOLFSBURG": "Вольфсбург",
  "VILLARREAL CF": "Вильярреал",
  ZENIT: "Зенит",
  
  CROATIA: "Хорватия",
  LITHUANIA: "Литва",
  ISRAEL: "Израиль",
  LATVIA: "Латвия",
  POLAND: "Польша",
  SERBIA: "Сербия",
  TURKEY: "Турция",
  DENMARK: "Дания"
};

export default glossary;