const translateCommand = {
  AUSTRALIA: "Австралия",
  FRANCE: "Франция",
  GREECE: "Греция",
  SLOVENIA: "Словения",
  SPAIN: "Испания",
  CANADA: "Канада",
  CHINA: "Китай",
  GERMANY: "Германия",
  ITALY: "Италия",
  RUSSIA: "Россия",
  BARCELONA: "Барселона",
  "CRVENA ZVEZDA": "Црвена Звезда",
  CSKA: "ЦСКА",
  FENERBAHCE: "Фенербахче",
  MACCABI: "Маккаби",
  OLYMPIACOS: "Олимпиакос",
  PANATHINAIKOS: "Панатинаикос",
  UNICS: "УНИКС",
  ZENIT: "Зенит",
  REAL: "Реал",
  FINLAND: "Финляндия",
  SWEDEN: "Швеция",
  USA: "США",
  "CZECH REPUBLIC": "Чехия",
  SWITZERLAND: "Швейцария",
};
